"use client";
import { useEffect,useState } from 'react';
import { Answer,type Message } from '@/components/answer';
type Correction={id:string;question:string;answer:string;source:string;status:string;preview:string|null};
type Data={conversations:{id:string;title:string;flagged:number}[];corrections:Correction[];documents:{id:string;title:string;url:string;retrieved:string}[];audit:{id:string;action:string;created:string}[]};
export default function Admin(){const [data,setData]=useState<Data|null>(null),[messages,setMessages]=useState<Message[]>([]),[question,setQuestion]=useState(''),[correction,setCorrection]=useState(''),[source,setSource]=useState(''),[filter,setFilter]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[title,setTitle]=useState('');
 async function load(){const r=await fetch('/api/admin');const d=await r.json() as Data;if(!r.ok)throw new Error('Could not load the panel.');setData(d)}
 useEffect(()=>{void load().catch(()=>setNotice('Could not load the panel. Reload to try again.'))},[]);
 async function act(action:string,extra:Record<string,string>={}){setBusy(true);setNotice('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||'Action failed.');await load();setNotice(action==='approve'?'Correction approved. Relevant future answers can now use it.':action==='test'?'Test answer ready below. Compare it with the official source before approving.':action==='refresh'?'Source refreshed and search index updated.':'Change saved.');if(action==='draft'){setQuestion('');setCorrection('');setSource('')}}catch(e){setNotice(e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}}
 async function open(id:string,label:string){try{const r=await fetch('/api/admin?conversation='+id);if(!r.ok)throw new Error();const d=await r.json() as {messages:Message[]};setMessages(d.messages);setTitle(label)}catch{setNotice('Could not load that conversation.')}}
 return <main className="admin"><div className="admin-header"><div><h1>Support desk</h1><p className="subtitle">AOM Scholar guide · Private local demo</p></div><a href="/">Open chat ↗</a></div><p className="notice">Learning is reviewed: save a correction → test the answer → verify the source → approve. User messages never become knowledge automatically.</p>{notice?<p role="status" className="notice">{notice}</p>:null}{!data?<p>Loading support desk…</p>:<div className="admin-grid"><div><section><h2>Conversations</h2><div className="scroll-list">{data.conversations.length?data.conversations.map(c=><button className="row-button" key={c.id} onClick={()=>void open(c.id,c.title)}>{c.title}{Number(c.flagged)>0?' · '+c.flagged+' flagged':''}</button>):<p>No conversations yet. Start in the chat.</p>}</div></section>
 <section><h2>Add a correction</h2><form onSubmit={e=>{e.preventDefault();void act('draft',{question,answer:correction,source})}}><label>Question or situation<input required minLength={5} maxLength={2500} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What question should this guidance help answer?"/></label><label>Verified guidance<textarea required minLength={5} maxLength={6000} rows={5} value={correction} onChange={e=>setCorrection(e.target.value)} placeholder="Write the correct guidance. Include the year for prices and deadlines."/></label><label>Official source URL<input required type="url" value={source} onChange={e=>setSource(e.target.value)} placeholder="Choose a source from the library below"/></label><button className="primary" disabled={busy}>Save draft</button></form></section>
 <section><h2>Knowledge library <small>({data.documents.length})</small></h2><input aria-label="Search source library" placeholder="Search titles or URLs…" value={filter} onChange={e=>setFilter(e.target.value)}/><div className="scroll-list">{data.documents.filter(d=>(d.title+' '+d.url).toLowerCase().includes(filter.toLowerCase())).map(d=><div className="record" key={d.id}><a href={d.url} target="_blank" rel="noopener noreferrer">{d.title} ↗</a><p><small>Retrieved {d.retrieved.slice(0,10)}</small></p><div className="actions"><button onClick={()=>setSource(d.url)}>Use source</button><button disabled={busy} onClick={()=>void act('refresh',{id:d.id})}>Refresh source</button></div></div>)}</div><small>These are public page extracts. Retrieval does not mean every fact has been manually verified. Refreshes are manual.</small></section>
 <section><h2>Activity</h2><div className="scroll-list">{data.audit.map(a=><p key={a.id}><small>{a.created.slice(0,16).replace('T',' ')} · {a.action.replaceAll('_',' ')}</small></p>)}</div></section></div>
 <div>{title?<section><h2>{title}</h2>{messages.length?messages.map((m,i)=><div className="record" key={m.id||i}><span className="status">{m.role}{m.feedback?' · '+m.feedback.replace('_',' '):''}</span><Answer message={m}/>{m.role==='assistant'?<button onClick={()=>{setQuestion(messages[i-1]?.content||'');setCorrection(m.content);setSource(m.sources?.[0]?.url||'')}}>Prepare correction</button>:null}</div>):<p>No messages in this conversation yet.</p>}</section>:null}<section><h2>Reviewed learning</h2>{data.corrections.length?data.corrections.map(c=><div className="record" key={c.id}><span className="status">{c.status}</span><p><strong>{c.question}</strong></p><p>{c.answer}</p><a href={c.source} target="_blank" rel="noopener noreferrer">Verify official source ↗</a>{c.preview?<div className="preview"><strong>Test answer — not yet proof of correctness</strong><Answer message={{role:'assistant',...JSON.parse(c.preview)}}/></div>:null}<div className="actions">{['draft','tested'].includes(c.status)?<><button disabled={busy} onClick={()=>void act('test',{id:c.id})}>Test answer</button><button className="primary" disabled={busy||c.status!=='tested'} onClick={()=>void act('approve',{id:c.id})}>Reviewed · approve</button><button disabled={busy} onClick={()=>void act('reject',{id:c.id})}>Reject</button></>:null}{c.status==='approved'?<button disabled={busy} onClick={()=>void act('revoke',{id:c.id})}>Revoke</button>:null}</div></div>):<p>No corrections yet. Flag an answer in the chat or add verified guidance here.</p>}</section></div></div>}</main>
}
