"use client";
import { useEffect, useRef, useState } from 'react';
import { ArrowUp, LoaderCircle, Plus, History, ThumbsUp, Flag } from 'lucide-react';
import { Answer, type Message } from '@/components/answer';
type Conversation={id:string;title:string};
export default function Home(){
 const [messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[id,setId]=useState(''),[conversations,setConversations]=useState<Conversation[]>([]);
 const tail=useRef<HTMLDivElement>(null),inFlight=useRef(false),creatingConversation=useRef(false);const historyMenu=useRef<HTMLDetailsElement>(null);const requestRef=useRef<{id:string;q:string;conversation:string}|null>(null);
 function closeHistory(restoreFocus=true){if(historyMenu.current){historyMenu.current.open=false;if(restoreFocus)historyMenu.current.querySelector('summary')?.focus();}}const action=useRef<(q:string)=>Promise<unknown>>(async()=>{});
 useEffect(()=>{function outside(event:PointerEvent){if(historyMenu.current?.open&&!historyMenu.current.contains(event.target as Node))closeHistory(false)}document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside)},[]);
 async function load(selected?:string){if(selected)closeHistory();setLoading(true);setError('');try{const r=await fetch('/api/session'+(selected?'?id='+selected:''));const data=await r.json() as {id:string;messages:Message[];conversations:Conversation[];error?:string};if(!r.ok)throw new Error(data.error);setConversations(data.conversations);if(data.id){setId(data.id);setMessages(data.messages)}else await newChat();}catch{setError('Could not load your conversation. Reload to try again.')}finally{setLoading(false)}}
 async function newChat(){
  closeHistory();
  if(creatingConversation.current||inFlight.current)return;
  if(id&&!messages.length){document.getElementById('question')?.focus();return;}
  creatingConversation.current=true;setLoading(true);setError('');
  try{
   const r=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'new'})});
   const data=await r.json() as {id:string};if(!r.ok)throw new Error('Could not start a conversation.');
   setId(data.id);setMessages([]);setDraft('');setConversations(c=>[{id:data.id,title:'New conversation'},...c.filter(item=>item.id!==data.id)]);
  }finally{creatingConversation.current=false;setLoading(false);}
 }

 useEffect(()=>{void load();},[]);
 useEffect(()=>{action.current=ask;});
 useEffect(()=>{tail.current?.scrollIntoView({behavior:'smooth'})},[messages,busy]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(t:unknown,o:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'ask_aom_guide',description:'Send an AOM question and save the sourced answer in the current conversation.',inputSchema:{type:'object',properties:{question:{type:'string',minLength:1,maxLength:2500}},required:['question'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const q=(input as {question?:unknown})?.question;if(typeof q!=='string'||!q.trim()||q.length>2500)throw new Error('A question of up to 2,500 characters is required.');return action.current(q)}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 async function ask(q:string){if(inFlight.current||loading||!id||!q.trim())return;inFlight.current=true;if(!requestRef.current||requestRef.current.q!==q||requestRef.current.conversation!==id)requestRef.current={id:crypto.randomUUID(),q,conversation:id};setBusy(true);setError('');const previous=messages;setMessages([...previous,{role:'user',content:q}]);setDraft('');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversationId:id,requestId:requestRef.current.id,question:q})});const data=await r.json() as Message & {error?:string};if(!r.ok)throw new Error(data.error||'Please try again.');setMessages([...previous,{role:'user',content:q},{...data,role:'assistant'}]);setConversations(c=>c.map(x=>x.id===id&&x.title==='New conversation'?{...x,title:q.slice(0,75)}:x));requestRef.current=null;return data}catch(e){setMessages(previous);setDraft(q);setError(e instanceof Error?e.message:'Please try again.');return {error:'Answer failed'}}finally{inFlight.current=false;setBusy(false)}}
 async function feedback(messageId:string,value:string){try{const r=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'feedback',messageId,feedback:value})});if(!r.ok)throw new Error();setMessages(m=>m.map(x=>x.id===messageId?{...x,feedback:value}:x))}catch{setError('Could not save feedback. Please try again.')}}
 return <main className="chat-shell"><header className="chat-header"><img src="/aom-logo.png" width="184" height="51" alt="Academy of Management"/></header>
 <div className="chat-tools"><details ref={historyMenu} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();closeHistory();}}}><summary><History size={16}/> Conversations</summary><div className="history-list">{conversations.map(c=><button disabled={busy||loading} key={c.id} onClick={()=>void load(c.id)} aria-current={c.id===id?'true':undefined}>{c.title}</button>)}</div></details><button disabled={busy||loading} onClick={()=>void newChat().catch(()=>setError('Could not start a conversation.'))}><Plus size={16}/> New chat</button></div>
 <section className="conversation" aria-label="Conversation" aria-live="polite">{loading?<p className="thinking">Loading conversation…</p>:!messages.length?<article className="message assistant"><p>Hi, I’m AOM Scholar guide. What can I help you with?</p><p className="chat-notice">Find your way around AOM, from membership and journals to conferences and events. Ask a question for clear guidance and links to official resources.</p></article>:messages.map((m,i)=><article key={m.id||i} className={`message ${m.role}`}><Answer message={m}/>{m.role==='assistant'&&m.id?<div className="feedback"><button aria-label="Helpful answer" aria-pressed={m.feedback==='helpful'} onClick={()=>feedback(m.id!,'helpful')}><ThumbsUp size={14}/>{m.feedback==='helpful'?'Thanks for your feedback':'Helpful'}</button><button aria-label="Flag answer for review" aria-pressed={m.feedback==='needs_review'} onClick={()=>feedback(m.id!,'needs_review')}><Flag size={14}/>{m.feedback==='needs_review'?'Sent for review':'Needs review'}</button></div>:null}</article>)}{busy?<div className="thinking" role="status"><LoaderCircle size={17} className="spin"/> Thinking…</div>:null}<div ref={tail}/></section>
 <div className="composer-area">{error?<p role="alert" className="error">{error}</p>:null}<form className="composer" onSubmit={e=>{e.preventDefault();void ask(draft)}}><label className="sr-only" htmlFor="question">Message AOM Scholar guide</label><textarea id="question" rows={1} maxLength={2500} value={draft} disabled={busy||loading||!id} onChange={e=>setDraft(e.target.value)} placeholder="Type your message…" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void ask(draft)}}}/><button aria-label="Send message" disabled={busy||loading||!id||!draft.trim()}>{busy?<LoaderCircle className="spin" size={20}/>:<ArrowUp size={21}/>}</button></form></div></main>
}
