import { z } from 'zod';
import { db,eq,uid,now,audit,history } from '@/lib/store';
import { answer } from '@/lib/answer';
import { access,json,body } from '@/lib/http';
export const dynamic='force-dynamic';export const maxDuration=60;
export async function GET(request:Request){try{access(request,true);const id=new URL(request.url).searchParams.get('conversation');if(id)return json({messages:await history(id)});const conversations=await db('aom_conversations?order=created.desc&limit=100');const corrections=await db('aom_corrections?order=created.desc');const documents=await db('aom_documents?select=id,title,url,retrieved&order=title.asc');const events=await db('aom_audit?order=created.desc&limit=30');const flags=await db('aom_messages?select=conversation&feedback=eq.needs_review');return json({conversations:conversations.map(c=>({...c,flagged:flags.filter(f=>f.conversation===c.id).length})),corrections,documents,audit:events})}catch{return json({error:'Sign in to the support desk.'},401)}}
export async function POST(request:Request){try{const input=z.object({action:z.enum(['draft','test','approve','reject','revoke','refresh']),id:z.string().optional(),question:z.string().trim().min(5).max(2500).optional(),answer:z.string().trim().min(5).max(6000).optional(),source:z.string().url().optional()}).parse(await body(request,true));
 if(input.action==='draft'){if(!input.question||!input.answer||!input.source||!(await db('aom_documents?url=eq.'+eq(input.source)+'&select=id')).length)return json({error:'Provide a question, guidance and a source from the knowledge library.'},400);const id=uid();await db('aom_corrections','POST',{id,question:input.question,answer:input.answer,source:input.source,status:'draft',created:now()});await audit('draft_created',id);return json({id})}
 if(input.action==='refresh'){const d=(await db('aom_documents?id=eq.'+eq(input.id||'')))[0];if(!d?.wpId)throw new Error('Source not found');const r=await fetch('https://www.aom.org/wp-json/wp/v2/pages/'+Number(d.wpId),{signal:AbortSignal.timeout(25000),redirect:'error'});if(!r.ok)throw new Error('Refresh failed; saved source is unchanged');const page=z.object({content:z.object({rendered:z.string()}),link:z.string().url()}).parse(await r.json());if(page.link!==d.url)throw new Error('Source URL changed; manual review required');const text=page.content.rendered.replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi,'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/\s+/g,' ').trim();if(text.length<100)throw new Error('No usable source text');await db('rpc/aom_index_document','POST',{document:{...d,text,retrieved:now()}});await audit('source_refreshed',String(d.id));return json({ok:true})}
 const c=(await db('aom_corrections?id=eq.'+eq(input.id||'')))[0];if(!c)throw new Error('Correction not found');const path='aom_corrections?id=eq.'+eq(String(c.id))+'&status=eq.'+eq(String(c.status));
 if(input.action==='test'){if(!['draft','tested'].includes(String(c.status)))throw new Error('Only pending corrections can be tested');const preview=await answer(String(c.question),[],c);if(!(await db(path,'PATCH',{preview:JSON.stringify(preview),status:'tested'})).length)throw new Error('Correction changed. Reload and try again.');await audit('correction_tested',String(c.id));return json({preview})}
 const allowed=input.action==='approve'?['tested']:input.action==='reject'?['draft','tested']:['approved'];if(!allowed.includes(String(c.status)))throw new Error('Test and review before approval; only approved corrections can be revoked');const status=input.action==='approve'?'approved':input.action==='reject'?'rejected':'revoked';if(!(await db(path,'PATCH',{status})).length)throw new Error('Correction changed. Reload and try again.');await audit('correction_'+status,String(c.id));return json({ok:true});
 }catch(e){return json({error:e instanceof Error&&/^(Provide|Source|Refresh|No usable|Only|Correction|Test)/.test(e.message)?e.message:'Could not save this change. Check your sign-in and try again.'},400)}}
